include(ExternalProject)

MACRO (INCLUDE_EXTERNAL_LIBRARY EXTERNAL_DIRECTORY)

    CMAKE_PARSE_ARGUMENTS(INCLUDE_EXTERNAL_LIBRARY
        ""
        ""
        ""
        ${ARGN}
    )

    set(CMAKE_PREFIX_PATH ${EXTERNAL_DIRECTORY}/install/${CMAKE_BUILD_TYPE})
ENDMACRO ()

MACRO (PREPARE_EXTERNAL_LIBRARY PACKAGE_NAME GITHUB_URL GITHUB_BRANCH PACKAGE_DEFINES RECURSIVE_SUBMODULE_BOOL)

    CMAKE_PARSE_ARGUMENTS(INCUDE_EXTERNAL_CMAKE
        ""
        ""
        ""
        ${ARGN}
    )

    set(PACKAGE_DOWNLOAD_DIR "${EXTERNAL_DIRECTORY}/packages/${PACKAGE_NAME}")
    set(PACKAGE_STAMP_DIR "${PACKAGE_DOWNLOAD_DIR}/${CMAKE_BUILD_TYPE}/STAMP_DIR")
    set(PACKAGE_BUILD_DIR "${PACKAGE_DOWNLOAD_DIR}/${CMAKE_BUILD_TYPE}/BUILD_DIR")
#    set(PACKAGE_INSTALL_DIR "${EXTERNAL_DIRECTORY}/install/${PACKAGE_NAME}")
    set(PACKAGE_INSTALL_DIR "${EXTERNAL_DIRECTORY}/install/${CMAKE_BUILD_TYPE}")

    ExternalProject_Add(${PACKAGE_NAME}
        GIT_REPOSITORY ${GITHUB_URL}
        GIT_TAG ${GITHUB_BRANCH}
	GIT_SUBMODULES_RECURSE ${RECURSIVE_SUBMODULE_BOOL}
	GIT_PROGRESS ${GIT_VERBOSITY}
        PREFIX ${PACKAGE_DOWNLOAD_DIR}
	STAMP_DIR ${PACKAGE_STAMP_DIR}
	BINARY_DIR ${PACKAGE_STAMP_DIR}
        INSTALL_DIR ${PACKAGE_INSTALL_DIR}
        CMAKE_ARGS -DCMAKE_INSTALL_PREFIX=${PACKAGE_INSTALL_DIR} -DCMAKE_PREFIX_PATH=${PACKAGE_INSTALL_DIR} -DCMAKE_BUILD_TYPE=${CMAKE_BUILD_TYPE} ${PACKAGE_DEFINES}
    )
    IF (IS_DIRECTORY "${PACKAGE_INSTALL_DIR}")
#       MESSAGE(STATUS "Found ${PACKAGE_INSTALL_DIR}")
       set(CMAKE_PREFIX_PATH ${PACKAGE_INSTALL_DIR})
#       list(PREPEND CMAKE_PREFIX_PATH ${PACKAGE_INSTALL_DIR})
    ENDIF()

ENDMACRO()

